interactive_comments chase_links
hist_fcntl_lock share_history notify
ignore_eof correct transient_rprompt

hist_verify hist_no_store
hist_reduce_blanks hist_lex_words
hist_ignore_dups hist_ignore_all_dups
hist_find_no_dups hist_save_no_dups
hist_no_store hist_expire_dups_first
extended_history

no_beep no_flow_control no_bang_hist
